import { externalSkillDiscoverySearchTerms } from "../../data/externalSkillDiscovery";
import { starterPackSearchTerms } from "../../data/starterPacks";
import {
  artifactHandle,
  promptArtifactType,
} from "../../promptUtils";
import type { PromptDefinition } from "../../types";
import { AGENT_WORKFLOW_COMMANDS } from "./agentWorkflowCommands";
import type { LauncherCommand } from "./launcherCommandTypes";

export const SCRATCH_COMMAND: LauncherCommand = {
  id: "scratch",
  label: "Scratch",
  description: "Temporary prompt.",
  category: "Scratch",
  keywords: ["compose", "draft", "temporary prompt", "one off"],
  aliases: ["scratch prompt", "임시 프롬프트"],
  homePlacement: "home",
  artifactRequirement: "none",
};

export const CAPTURE_CLIPBOARD_COMMAND: LauncherCommand = {
  id: "capture-clipboard",
  label: "Capture Clipboard",
  description: "Save current clipboard as temporary context.",
  category: "Clipboard",
  keywords: ["clip", "context", "copy", "paste", "stack"],
  aliases: ["clipboard context", "클립보드", "컨텍스트 캡처"],
  homePlacement: "home",
  artifactRequirement: "none",
  privacyLabel: "Reads the current clipboard only when explicitly run.",
};

export const HISTORY_COMMANDS: LauncherCommand[] = [
  {
    id: "run-last-prompt",
    label: "Run Last Prompt",
    description: "Prepare the most recent deliverable artifact from usage history.",
    category: "History",
    keywords: ["history", "recent", "last", "again", "rerun", "repeat", "prompt"],
    aliases: ["last prompt", "repeat prompt", "최근 프롬프트", "다시 실행"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Uses usage metadata only: artifact id, timestamp, delivery mode, and result.",
  },
  {
    id: "open-recent-context-stack",
    label: "Open Clipboard Stack",
    description: "Open explicitly captured clipboard contexts.",
    category: "Clipboard",
    keywords: ["history", "recent", "context", "clipboard", "clip", "stack"],
    aliases: ["context stack", "recent contexts", "clipboard stack", "최근 컨텍스트", "클립 스택"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Opens only explicitly captured local clipboard contexts that have not expired.",
  },
  {
    id: "clear-expired-contexts",
    label: "Clear Expired Contexts",
    description: "Prune expired temporary context files and reload the local library.",
    category: "History",
    keywords: ["history", "clear", "cleanup", "expired", "context", "clipboard", "ttl"],
    aliases: ["cleanup contexts", "clear old contexts", "만료 컨텍스트 삭제"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Reloads the local library and removes only expired ephemeral context files.",
  },
  {
    id: "reveal-last-failed-delivery",
    label: "Reveal Last Failed Delivery",
    description: "Show the latest failed delivery metadata without private content.",
    category: "History",
    keywords: ["history", "recovery", "failed", "failure", "delivery", "diagnostic"],
    aliases: ["last failure", "failed delivery", "최근 실패", "전송 실패"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Shows only failure metadata: artifact id, timestamp, delivery mode, result, target app, and diagnostic code.",
  },
];

export const LIBRARY_HOME_COMMAND: LauncherCommand = {
  id: "browse-library",
  label: "Browse Library",
  description: "Browse local artifact inventory.",
  category: "Library",
  keywords: ["browse", "library", "inventory", "artifacts"],
  aliases: ["local library", "inventory", "what do I have", "라이브러리 보기"],
  homePlacement: "home",
  artifactRequirement: "none",
  privacyLabel: "Shows handles, titles, lifecycle, and source metadata only.",
};

export const LIBRARY_BROWSE_COMMANDS: LauncherCommand[] = [
  {
    id: "browse-prompts",
    label: "Browse Prompts",
    description: "Browse local prompt inventory.",
    category: "Library",
    keywords: ["browse", "library", "inventory", "prompts", "prompt", "slash"],
    aliases: ["prompt library", "show prompts", "프롬프트 목록", "프롬프트 라이브러리"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Shows prompt handles, titles, and local metadata only.",
  },
  {
    id: "browse-contexts",
    label: "Browse Contexts",
    description: "Browse saved local contexts.",
    category: "Library",
    keywords: ["browse", "library", "inventory", "contexts", "context", "at"],
    aliases: ["context library", "show contexts", "컨텍스트 목록", "컨텍스트 라이브러리"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Shows context handles, titles, lifecycle, and local metadata only.",
  },
  {
    id: "browse-skills",
    label: "Browse Skills",
    description: "Browse installed SKILL.md packages.",
    category: "Library",
    keywords: ["browse", "library", "inventory", "skills", "skill", "SKILL.md"],
    aliases: ["installed skills", "show skills", "스킬 목록", "스킬 라이브러리"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Shows skill handles, titles, source metadata, and actions only.",
  },
  {
    id: "browse-commands",
    label: "Browse Commands",
    description: "Browse built-in and user-defined Launcher commands.",
    category: "Library",
    keywords: ["browse", "library", "inventory", "commands", "command", "launcher"],
    aliases: ["command library", "show commands", "명령 목록", "런처 명령"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Shows command titles, categories, aliases, and local package metadata only.",
  },
];

export const MANAGEMENT_COMMANDS: LauncherCommand[] = [
  {
    id: "add-prompt",
    label: "New Prompt",
    description: "Create a prompt from Launcher.",
    category: "Create",
    keywords: ["create", "new", "prompt", "slash command"],
    aliases: ["create prompt", "새 프롬프트", "프롬프트 만들기"],
    homePlacement: "home",
    artifactRequirement: "none",
  },
  {
    id: "add-context",
    label: "New Context",
    description: "Create context from Launcher.",
    category: "Create",
    keywords: ["create", "new", "context", "at context"],
    aliases: ["create context", "새 컨텍스트", "컨텍스트 만들기"],
    homePlacement: "home",
    artifactRequirement: "none",
  },
  {
    id: "add-skill",
    label: "New Skill",
    description: "Create a persistent SKILL.md package.",
    category: "Create",
    keywords: ["create", "new", "skill", "workflow", "SKILL.md"],
    aliases: ["create skill", "새 스킬", "스킬 만들기"],
    homePlacement: "search",
    artifactRequirement: "none",
  },
  {
    id: "browse-packs",
    label: "Browse Packs",
    description: "Discover starter packs before previewing a GitHub import.",
    category: "Import",
    keywords: ["browse", "starter", "packs", "pack", "discover", ...starterPackSearchTerms()],
    aliases: ["starter packs", "browse packs", "팩 둘러보기", "팩 찾기"],
    homePlacement: "home",
    artifactRequirement: "none",
    privacyLabel: "Uses local pack metadata until you explicitly preview a GitHub pack.",
  },
  {
    id: "discover-skills",
    label: "Discover Skills",
    description: "Review external skill sources behind a local import gate.",
    category: "Import",
    keywords: ["discover", "skills", "agent skills", "directory", ...externalSkillDiscoverySearchTerms()],
    aliases: ["skills.sh", "skill discovery", "스킬 찾기", "스킬 디스커버리"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Shows local discovery gate metadata only and sends no local project or library content.",
  },
  {
    id: "find-agent-skills",
    label: "Find Agent Skills",
    description: "Start external agent-skill discovery without scanning local context.",
    category: "Import",
    keywords: ["find", "agent", "skills", "external", "directory", ...externalSkillDiscoverySearchTerms()],
    aliases: ["find skills", "agent skill search", "에이전트 스킬 찾기"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Does not send project contents, prompt bodies, context bodies, terminal output, clipboard history, or agent output.",
  },
  {
    id: "install-agent-skill",
    label: "Install Agent Skill...",
    description: "Open the gated external skill install path.",
    category: "Import",
    keywords: ["install", "agent", "skill", "external", "skills.sh", "npx", "github"],
    aliases: ["install external skill", "add agent skill", "외부 스킬 설치"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Does not run external installers or write files before explicit GitHub preview and import.",
  },
  {
    id: "review-installed-skills",
    label: "Review Installed Skills",
    description: "Open installed local SKILL.md packages.",
    category: "Library",
    keywords: ["review", "installed", "skills", "local", "SKILL.md"],
    aliases: ["installed skill review", "스킬 검토", "설치된 스킬"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Shows installed skill handles, titles, source path, and local metadata only.",
  },
  {
    id: "import-github",
    label: "Import from GitHub",
    description: "Preview a repository pack before writing local packages.",
    category: "Import",
    keywords: ["github", "gh", "repo", "repository", "pack", "library pack"],
    aliases: ["gh import", "github pack", "가져오기", "깃허브 가져오기"],
    homePlacement: "search",
    artifactRequirement: "none",
    privacyLabel: "Imports only after an explicit preview/write flow.",
  },
  {
    id: "project-setup",
    label: "Project Setup",
    description: "Choose a starter-pack preset and preview project files.",
    category: "Project",
    keywords: [
      "project",
      "setup",
      "install",
      "export",
      "agents",
      "AGENTS.md",
      "codex",
      "starter pack",
      ...starterPackSearchTerms(),
    ],
    aliases: ["project install", "workspace setup", "starter setup", "프로젝트", "프로젝트 설치", "프로젝트 설정"],
    homePlacement: "home",
    artifactRequirement: "none",
    privacyLabel: "Project files are written only after preview and confirmation.",
  },
  {
    id: "export-prompt-project",
    label: "Export Prompt to Project...",
    description: "Preview exact project files before writing.",
    category: "Project",
    keywords: ["project", "export", "prompt", "install", ".ult"],
    aliases: ["project prompt", "프롬프트 내보내기", "프로젝트 프롬프트"],
    homePlacement: "search",
    artifactRequirement: "prompt",
    privacyLabel: "Writes only after explicit preview and confirmation.",
  },
  {
    id: "export-context-project",
    label: "Export Context to Project...",
    description: "Preview exact project files before writing.",
    category: "Project",
    keywords: ["project", "export", "context", "install", ".ult"],
    aliases: ["project context", "컨텍스트 내보내기", "프로젝트 컨텍스트"],
    homePlacement: "search",
    artifactRequirement: "context",
    privacyLabel: "Writes only after explicit preview and confirmation.",
  },
  {
    id: "install-skill-project",
    label: "Install Skill to Project...",
    description: "Preview the .codex skill file before writing.",
    category: "Project",
    keywords: ["project", "install", "skill", "codex", ".codex", "SKILL.md"],
    aliases: ["project skill", "프로젝트 설치", "스킬 설치"],
    homePlacement: "search",
    artifactRequirement: "skill",
    privacyLabel: "Writes only after explicit preview and confirmation.",
  },
  {
    id: "create-agents-snippet",
    label: "Create AGENTS.md Snippet...",
    description: "Preview AGENTS.md before writing.",
    category: "Project",
    keywords: ["project", "agents", "AGENTS.md", "instructions", "codex"],
    aliases: ["agents snippet", "프로젝트 지침", "에이전트 지침"],
    homePlacement: "search",
    artifactRequirement: "any",
    privacyLabel: "Writes only after explicit preview and confirmation.",
  },
  {
    id: "open-library",
    label: "Reveal Library Folder",
    description: "Open ~/.ult/personal-library in Finder.",
    category: "Library",
    keywords: ["library", "folder", "finder", "reveal", "personal library"],
    aliases: ["open library", "라이브러리", "폴더 열기"],
    homePlacement: "search",
    artifactRequirement: "none",
  },
  {
    id: "preferences",
    label: "Preferences",
    description: "Settings.",
    category: "Settings",
    keywords: ["settings", "config", "configuration", "shortcuts", "appearance"],
    aliases: ["settings", "환경설정", "설정"],
    homePlacement: "home",
    artifactRequirement: "none",
  },
];

export const STATIC_COMMANDS: LauncherCommand[] = [
  SCRATCH_COMMAND,
  CAPTURE_CLIPBOARD_COMMAND,
  ...AGENT_WORKFLOW_COMMANDS,
  ...HISTORY_COMMANDS,
  LIBRARY_HOME_COMMAND,
  ...LIBRARY_BROWSE_COMMANDS,
  ...MANAGEMENT_COMMANDS,
];

export const BASE_COMMANDS: LauncherCommand[] = STATIC_COMMANDS;

export function artifactCommand(prompt: PromptDefinition): LauncherCommand {
  return {
    id: "load-artifact",
    label: artifactHandle(prompt),
    description: prompt.title,
    homePlacement: "home",
    artifactRequirement: promptArtifactType(prompt),
    artifactId: prompt.id,
    artifactType: promptArtifactType(prompt),
  };
}
